# Namespace for sample application with eventing enabled
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing-websocket-source
  labels:
       knative-eventing-injection: enabled
---
# Helloworld-go app deploment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wseventsource
  namespace: knative-eventing-websocket-source
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: wseventsource
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: wseventsource
          image: docker.io/josiemundi/wssource
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: wsservice
---
# Service that exposes wseventsource app.
# This will be the subscriber for the Trigger
  kind: Service
  apiVersion: v1
  metadata:
    name: wsservice
    namespace: knative-eventing-websocket-source
  spec:
    selector:
      app: wseventsource
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# Knative Eventing Trigger to trigger the helloworld-go service
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: wsevent-trigger
  namespace: knative-eventing-websocket-source
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.wsevent
      source: knative-eventing-websocket-source/wseventsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: wseventsource