# Namespace for sample application with eventing enabled
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing-websocket-source
  labels:
       knative-eventing-injection: enabled
---
# Helloworld-go app deploment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wseventsource
  namespace: knative-eventing-websocket-source
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: wseventsource
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: wseventsource
          image: docker.io/josiemundi/wssource
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
---
# Service that exposes wseventsource app.
# This will be the subscriber for the Trigger
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
    template:
      metadata:
        # annotations:
        #   autoscaling.knative.dev/target: "2"
      spec:
        container:
          image: gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display@sha256:1d6ddc00ab3e43634cd16b342f9663f9739ba09bc037d5dea175dc425a1bb955

---
# Knative Eventing Trigger to trigger the helloworld-go service
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: wsevent-trigger
  namespace: knative-eventing-websocket-source
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.wsevent
      source: knative-eventing-websocket-source/wseventsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display